### ISSUE TITLE
Don't re-advertise the extension after it's already installed

### ISSUE THREAD

**Issue by ssokolow** [ehsan/popup-reporter#2]
It is reasonable to expect that a user will already have read the contents of the left half of the browser action popup on the AMO page before installing the extension, so duplicating them in the extension is actively counter-productive.

1. It wastefully doubles the size of the popup
2. It's such a divergence from design conventions that it may actively confuse users by making them question correct assumptions about how the UI is supposed to be interacted with.
3. It risk irritating users... ironically, in an extension they'll have installed specifically to fight irritations.
4. It violates the principle of only showing users actionable information. (They already took the action of installing the extension the first time they saw it.)

I recommend just cutting the popup down to the right half.

**Comment by ehsan** [comment]
Fixed!
