### ISSUE TITLE
Browser action icon draws undesired attention by not following Firefox style guidelines

### ISSUE THREAD

**Issue by ssokolow** [ehsan/popup-reporter#3]
Firefox UI guidelines expect colour to be used to draw attention. For example, via a notification badge.

Icons which are merely there to be clicked at the user's discretion should be monochrome and uniform in their colour scheme.

Here's the relevant of the Photon Design System manual:

https://design.firefox.com/photon/visuals/iconography.html#color

If nothing else, recolor the icon from pale blue on white to `rgba(12, 12, 13, 0.8)` (light background) or `rgba(249, 249, 250, 0.8)` on transparent.

The `browser_action` documentation explains how to specify different icons for light and dark use:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/browser_action

**Comment by ehsan** [comment]
Fixed in #10.
