### ISSUE TITLE
Consider  using a page action instead of a browser action

### ISSUE THREAD

**Issue by ssokolow** [ehsan/popup-reporter#4]
While the specific language has been dropped from current versions of the Chrome and Firefox API documentation, the original rationale for the split between page and browser actions was as follows, and it's still very valid:

* A page action is an action which applies to the current document, such as "Share this page", "Bookmark this page", "Screenshot this page", or, in your case, "Report this page". They are drawn inside the address bar to make that relationship between the URL and the icon intuitively obvious.

* A browser action is an action which has implications beyond the current document, such as changing policy settings for whole domains (eg. NoScript/uMatrix, uBlock, Self-Destroying Cookies, etc.) or affecting the browser itself (eg. Back/Forward, Tree Style Tab, Downloads, etc.) This impression is reinforced by placing them at the same level as the hamburger menu.

Given that context, it makes more sense for this to use a page action rather than a browser action.

It also removes the need to have separate dark and light forms of the icon as I mention in #3 since the address bar always has a light background.

**Comment by ehsan** [comment]
Fixed as well.
