### ISSUE TITLE
Move icon attribution to the addon's about:addons page

### ISSUE THREAD

**Issue by ssokolow** [ehsan/popup-reporter#5]
While unreasonable copyright holders do exist, there are generally agreed-upon places for attribution to go in software so that it doesn't interfere with the design of the site or application.

For websites, it would be the site footer or in a separate credits/acknowledgements page linked from the footer.

For native applications, it would be in the About dialog.

The closest analogue for a Firefox extension would be the about:addons page for the extension.

(It should also work around the irritating Firefox bug where Firefox ignores my "force all new windows to open as tabs on the current window" preference if you click on a citation link in a browser action panel.)

If you don't mind including literal URLs rather than hyperlinks, you can include it at the bottom of the AMO extension description which gets displayed when you choose "More" in about:addons.

Failing that, while it's not technically "Preferences", you can use something like this to allow you to tack arbitrary HTML onto the bottom of your about:addons More page.

```json
  "options_ui": {
    "browser_style": true,
    "page": "options_ui/options.html"
  }
```

**EDIT:** You will also want to correct the in-source licensing information, so I'd suggest doing the following:

1. Move your current `LICENSE` file to `LICENSE.mpl2`
2. Add a new `LICENSE` file with a message which says something like this:

```
Files within extensions/icons/ designed by Smartline from Flaticon and used 
under the terms of the CC-BY 3.0.

Other files are released under the terms of the Mozilla Public License version 2.0.
See LICENSE.mpl2 for details.
```

**Comment by ehsan** [comment]
Fixed too.
