### ISSUE TITLE
Icon attribution's phrasing is awkward

### ISSUE THREAD

**Issue by ssokolow** [ehsan/popup-reporter#6]
The phrasing "Icon used by the extension made by Smartline from www.flaticon.com is licensed by CC 3.0 BY" has multiple issues which should be corrected:

1. "CC 3.0 BY" is incorrect and should be replaced by "CC-BY 3.0" ("CC-BY" is the official abbreviation of the license and putting the version number in the middle incorrectly implies that all CC licenses receive version updates at the same time as part of a pack.")

2. The proper terminology is "licensed under" or "used under", not "licensed by". ("licensed by" refers to the copyright holder who chose to apply the license to the content.)

3. The sentence is needlessly verbose.

Since you're using it as "the" icon for the extension, here's what I'd suggest putting, with a URL, at the bottom of your AMO description to be picked up by the "More" page under about:addons:

"Extension icon by Smartline from Flaticon. Used under the CC-BY 3.0 license."

(Also, did you contact Smartline to get a custom license? I've been poking through Smartline's icons on Flaticon and, so far, all the ones I've seen have been under the Flaticon Basic License.)

**Comment by MikkCZ** [comment]
Looking at #10, the formulation will go away.

**Comment by ehsan** [comment]
This is fixed now.  FWIW the icon I'm using is also under the Flaticon Basic License.
