### ISSUE TITLE
Clicking extension button from overflow menu doesn't work

### ISSUE THREAD

**Issue by djc** [ehsan/popup-reporter#8]
I've put the extension button in the overflow menu. After I click the button (for example, on https://www.newyorker.com/news/daily-comment/donald-trump-and-the-craven-firing-of-andrew-mccabe?utm_source=nextdraft&utm_medium=email), the overflow menu disappears, but the extension panel does not appear. On subsequent clicks of the overflow menu button, even the overflow menu itself does not appear.

**Comment by MikkCZ** [comment]
I cannot reproduce the issue. However #10 would resolve this too by moving to page action.

**Comment by djc** [comment]
Well, so far I've been unable to actually use the extension. As soon as I click the button from the overflow menu, the browser just hangs for a while. It will recover after several seconds, but it won't show the modal dialog for the extension.

**Comment by ehsan** [comment]
The new version of the extension (1.6) moves it to inside the URL bar.  I think that sort of addresses your issue @djc, can you please retest?  Thanks!

**Comment by djc** [comment]
Yup, seems to work better now.
