### ISSUE TITLE
New design for panel

### ISSUE THREAD

**Issue by sevaan** [ehsan/popup-reporter#9]
Hi all,

This is the design for the current panel: 

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/473531/37680238-ae47c91c-2c59-11e8-96a9-e57003fc3db0.png">

- It doesn't really conform with out other panels in Firefox looks.
- The example image is too distracting, and isn't related to the page.
- The icon in the URL bar has a lot going on in it.
- I think the URL is irrelevant to the user...especially on super complex URLs, I don't think it adds much context.
- The note field is too big as well.

Here's an updated design: 

<img width="419" alt="image" src="https://user-images.githubusercontent.com/473531/37680360-086cc8a2-2c5a-11e8-9b60-1b94194e3f5b.png">

- I made a couple text changes, but really someone from Context Strategy should give it a look over.
- I remove the URL, and instead added the favicon of the page so the user knows it's related to the tab they are on
- I shrunk the notes field and added a clear report button.

Notes:

- Clicking off this panel should close it immediately.
- Once a user clicks the report button, we have two options:

Option A: Just close the panel and pulse the icon once in the URL bar (see how the DRM button pulses the first time you play DRM context).
<img width="30" alt="image" src="https://user-images.githubusercontent.com/473531/37680454-5c6d9850-2c5a-11e8-8228-ab7daecd8f64.png">

Or Option B: Shrink the panel and show a tiny "Thanks!" That disappears in 2 seconds, or if the user clicks off of it.
<img width="171" alt="image" src="https://user-images.githubusercontent.com/473531/37680459-6309df5c-2c5a-11e8-99f1-bddbb62f0c7d.png">

**Comment by ehsan** [comment]
@bwinton How about using a generic popup icon here, like something similar to what's in this screenshot?  (see my review comment on #10)
